# Generated by Django 5.2.9 on 2025-12-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDecisionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.BigIntegerField()),
                ('candidate_id', models.BigIntegerField()),
                ('title_a', models.TextField(blank=True, null=True)),
                ('title_b', models.TextField(blank=True, null=True)),
                ('image_a', models.TextField(blank=True, null=True)),
                ('image_b', models.TextField(blank=True, null=True)),
                ('visual_score', models.FloatField(blank=True, null=True)),
                ('text_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
                ('active_weights', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'cluster_decision_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
