# Generated by Django 5.2.9 on 2025-12-18 15:31

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clusterdecisionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('prep_days', models.IntegerField(default=30)),
                ('keywords', models.TextField(help_text='Keywords base para generar el vector')),
                ('embedding', core.models.VectorField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'future_events',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='embedding',
            field=core.models.VectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='intent_validation_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='semantic_coherence_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='suggested_parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='taxonomy_type',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_platform',
            field=models.CharField(blank=True, default='dropi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxonomy_concept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxonomy_industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxonomy_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='embedding_visual',
            field=core.models.VectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='analysis_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='concept_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='discard_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='dropi_competition_tier',
            field=models.CharField(blank=True, default='LOW', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='market_avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='market_opportunity_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='market_saturation_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='potential_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='search_volume_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='seasonality_flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='taxonomy_type',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='trend_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='validation_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MarketIntelligenceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('data_point', models.CharField(max_length=100)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('embedding_context', core.models.VectorField(blank=True, null=True)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, db_column='cluster_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_logs', to='core.uniqueproductcluster')),
            ],
            options={
                'db_table': 'market_intelligence_logs',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marketplace', models.CharField(max_length=50)),
                ('feedback_type', models.CharField(max_length=20)),
                ('text_content', models.TextField()),
                ('embedding', core.models.VectorField(blank=True, null=True)),
                ('posted_at', models.DateField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.category')),
            ],
            options={
                'db_table': 'marketplace_feedback',
            },
        ),
    ]
